// Project Lab - NHTV Igad

#pragma once

#include "Abilities/DealDamageProxy.h"
#include "PreCastAbilityEventGroup.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API APreCastAbilityEventGroup : public ADealDamageProxy
{
	GENERATED_BODY()
public:

	virtual void BeginPlay() override final;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason);
	virtual void Tick(float DeltaSeconds) override final;

	void StartAbility();
	static APreCastAbilityEventGroup* InitPreCast(UAbilityInfo* info, ANetworkCharacter* character);
private:
	UFUNCTION()
	void m_OnCharacterDestroyed();
};
