// Project Lab - NHTV Igad

#pragma once

#include "GlobalEditorUtilityBase.h"
#include "FixupUtility.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API UFixupUtility : public UGlobalEditorUtilityBase
{
	GENERATED_BODY()

public:
	UFUNCTION(BlueprintCallable, Category="HACKS")
	void FixupAbilityInfos();
	UFUNCTION(BlueprintCallable, Category = "HACKS")
	void FixAICastRanges(const FString& filter, float setRange, bool evenIfNotZero = false);
	UFUNCTION(BlueprintCallable, Category = "HACKS")
	void FixupSpawners();
	UFUNCTION(BlueprintCallable, Category = "HACKS")
	void CrashTheEditor();
};
