// Project Lab - NHTV Igad

#pragma once

#include "Spawners/KOTHSpawnerBase.h"
#include "KOTHMinionSpawner.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API AKOTHMinionSpawner : public AKOTHSpawnerBase
{
	GENERATED_BODY()
public:
	AKOTHMinionSpawner(const FObjectInitializer& init);
	virtual void GetNewTarget(class ANPCBase* mob)override;
	virtual void BeginPlay()override;
	virtual void Tick(float deltaTime) override;

	

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "KOTH Spawner Properties")
	FText CampName;

private:
	virtual void m_RespawnMobs()override;
	float kothagroRadius;
	float kothdeagroRadius;
};
