// Project Lab - NHTV Igad

#pragma once

#include "MenuScreen.h"
#include "GraphicsMenu.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API UGraphicsMenu : public USideView
{
	GENERATED_BODY()
	
public:
	virtual void NativeTick(const FGeometry& MyGeometry, float InDeltaTime) override;
	
	UFUNCTION(BlueprintCallable, Category = "Graphics")
	void InitButtons(class USelectButton* templateButton, TArray<class USelectButton*> settingButtons);

	UFUNCTION(BlueprintCallable, Category = "Graphics")
	void Apply();

private:
	void m_Update();

	USelectButton* m_templateButton;
	TArray<USelectButton*> m_settingButtons;

	int32 m_previousSelection;
};
