// Project Lab - NHTV Igad

#pragma once

#include "Blueprint/UserWidget.h"
#include "MapData.generated.h"

UCLASS(BlueprintType)
class UMapData : public UDataAsset
{
	GENERATED_BODY()

public:
	UMapData();
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Level")
	FString friendlyName;
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Level")
	FString description;
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Level",
	meta = (ClampMin = "2", ClampMax = "4", UIMin = "2", UIMax = "4"))
	int32 maxTeamCount;
	UPROPERTY(EditDefaultsOnly, BlueprintReadOnly, Category = "Level")
	UTexture2D* icon;
	UPROPERTY(BlueprintReadOnly, Category = "Level")
	FString pathToAsset;
};