// Project Lab - NHTV Igad

#pragma once
#include <map>
#include "Abilities/ConeTrigger.h"
#include "poisonAuraTrigger.generated.h"

/**
 * 
 */


UCLASS()
class UNREALPROJECT_API ApoisonAuraTrigger : public AConeTrigger
{
	GENERATED_BODY()
public:
	ApoisonAuraTrigger();

	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;
	virtual void HitEvent(class ANetworkCharacter* otherActor)override;
	virtual void LeaveEvent(class ANetworkCharacter* otherActor)override;
	UPROPERTY()
		TMap<class ANetworkCharacter*, class AModifier* > playerMap;
	UPROPERTY(meta = (ExposeOnSpawn), BlueprintReadWrite)
		float damage;
};
