// Project Lab - NHTV Igad

#pragma once

#include "Engine/DataAsset.h"
#include "TeamData.generated.h"

/**
 * 
 */

USTRUCT()
struct UNREALPROJECT_API FTeamDataStruct
{
	GENERATED_BODY()
public:
	UPROPERTY(EditDefaultsOnly)
	int32 team;
	UPROPERTY(EditDefaultsOnly)
	FLinearColor color;
};


UCLASS(BlueprintType)
class UNREALPROJECT_API UTeamData : public UDataAsset
{
	GENERATED_BODY()
	
public:
	UPROPERTY(EditDefaultsOnly)
		TArray<FTeamDataStruct> teamColors;
	
	UFUNCTION(BlueprintCallable, Category="Team Data")
	FLinearColor GetTeamColor(int32 team);
	
};
