// Project Lab - NHTV Igad

#pragma once

#include "GUI/Menu/MenuButton.h"
#include "EffectSlot.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API UEffectSlot : public UMenuButton
{
	GENERATED_BODY()

public:
	virtual void NativeConstruct();

	UFUNCTION(BlueprintCallable, Category = "EffectSelector")
	void Init(class UAbilityInfo* ability);

	UFUNCTION(BlueprintImplementableEvent, Category = "EffectSelector")
	void OnInit(class UAbilityInfo* ability);

	UPROPERTY(BlueprintReadOnly)
	class UAbilityInfo* ability;

private:
	UImage* m_image;
	UTextBlock* m_name;
};
