// Project Lab - NHTV Igad

#pragma once

#include "Creatures/NPCBase.h"
#include "BossBase.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API ABossBase : public ANPCBase
{
	GENERATED_BODY()
public: 
	ABossBase();
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
	virtual void Tick(float deltaTime) override;
	virtual void NativeOnKilled(class ANetworkCharacter* killer, class UAbilityInfo* ability) override;
protected:
	virtual void m_Engaged();
	virtual void m_Disengaged();
	float timer;
private:
	UPROPERTY()
	class AMusicPlayer* m_musicPlayer;
};
