// Project Lab - NHTV Igad

#pragma once

#include "Blueprint/UserWidget.h"
#include "ScoreBoard.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API UScoreBoard : public UUserWidget
{
	GENERATED_BODY()
	
	
public:
	UScoreBoard(const FObjectInitializer& init);

	UPROPERTY(EditAnywhere, Category = "Score Board")
		TSubclassOf<class UScoreBoardSlot> scoreBoardSlot;

	UFUNCTION(BlueprintCallable, Category = "Score Board")
	void Init(class UVerticalBox* container);

	UFUNCTION(BlueprintCallable, Category = "Score Board")
	void UpdateScoreBoard(int32 sort);

	UPROPERTY(BlueprintReadonly, Category = "SCore Board")
		class UTeamData* teamData;
private:
	class UVerticalBox* m_container;
	TArray<class UScoreBoardSlot*> m_slots;
};
