// Project Lab - NHTV Igad

#pragma once

#include "ProjectileBase.h"
#include "BombProjectile.generated.h"

UCLASS()
class UNREALPROJECT_API ABombProjectile : public AProjectileBase
{
	GENERATED_BODY()
	
public:
	ABombProjectile();

	virtual void BeginPlay() override;

	UPROPERTY(BlueprintReadWrite, Replicated, Category = "BombProjectile", meta = (ExposeOnSpawn))
	FVector source;
	UPROPERTY(BlueprintReadWrite, Replicated, Category = "BombProjectile", meta = (ExposeOnSpawn))
	FVector target;
	UPROPERTY(BlueprintReadWrite, Replicated, Category = "BombProjectile", meta = (ExposeOnSpawn))
	float travelTime;
	UPROPERTY(BlueprintReadWrite, Replicated, Category = "BombProjectile", meta = (ExposeOnSpawn))
	float travelHeight;
	virtual void NativeFixedProjectileTick(float DeltaTime) override;

private:
	float m_progress;
};
