// Project Lab - NHTV Igad

#pragma once
#include "Abilities/ConeTrigger.h"
#include "IntimidatingAuraTrigger.generated.h"

/**
 * 
 */
USTRUCT()
struct FIntimidatingAuraPair
{
	GENERATED_BODY()
public:
	FIntimidatingAuraPair(){}
	FIntimidatingAuraPair(class AModifier* m0, class AModifier*m1) { modifier0 = m0; modifier1 = m1; }
	UPROPERTY()
	class AModifier* modifier0;
	UPROPERTY()
	class AModifier* modifier1;
};

UCLASS()
class UNREALPROJECT_API AIntimidatingAuraTrigger : public AConeTrigger
{
	GENERATED_BODY()
	public:
	AIntimidatingAuraTrigger();

	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;
	virtual void HitEvent(class ANetworkCharacter* otherActor)override;
	virtual void LeaveEvent(class ANetworkCharacter* otherActor)override;
	UPROPERTY()
		TMap<class ANetworkCharacter*, FIntimidatingAuraPair > playerMap;
	UPROPERTY(meta = (ExposeOnSpawn), BlueprintReadWrite)
	float attackSpeedMultiplier;
	UPROPERTY(meta = (ExposeOnSpawn), BlueprintReadWrite)
	float MovementSpeedMultiplier;


};
