// Project Lab - NHTV Igad

#pragma once

#include "GameFramework/Actor.h"
#include "Shrine.generated.h"

UCLASS()
class UNREALPROJECT_API AShrine : public AActor
{
	GENERATED_BODY()
	
public:	
	// Sets default values for this actor's properties
	AShrine();
	

	UPROPERTY(VisibleAnywhere, Category = "Respawn")
	class UStaticMeshComponent* displayMesh;
	UPROPERTY(EditAnywhere, Category = "Respawn")
	class USphereComponent* shrineTrigger;

	UFUNCTION()
	void OnOverlapBegin(class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult);
	UFUNCTION()
	void OnOverlapEnd(class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);

};
