// Project Lab - NHTV Igad

#pragma once

#include "Abilities/ConeTrigger.h"
#include "AuraTrigger.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API AAuraTrigger : public AConeTrigger
{
	GENERATED_BODY()
	
public:
	virtual void Tick(float DeltaSeconds) override;	
	UFUNCTION(BlueprintCallable, category = "Trigger")
	class AModifier* GetModifier(class ANetworkCharacter* targetCharacter);
	UFUNCTION(BlueprintCallable, category = "Trigger")
	void SetModifier(class ANetworkCharacter* targetCharacter, AModifier* modifier);
	UPROPERTY()
	TMap<class ANetworkCharacter*, class AModifier*> data;
	UPROPERTY(BlueprintReadWrite, Category = "Ability", meta = (ExposeOnSpawn))
		AActor* followObject;
};
