// Project Lab - NHTV Igad

#pragma once

#include "Blueprint/UserWidget.h"
#include "IngameSkillTree.h"
#include "SpellInfoDisplay.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API USpellInfoDisplay : public UUserWidget
{
	GENERATED_BODY()
	
public:
	void NativeConstruct() override;
	void OnLevelUp(class ANetworkPlayer* player, TArray<FIngameSkillTreeSkill> updatedSkills);

	UPROPERTY(BlueprintReadWrite)
	ANetworkPlayer* player;

	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<class USpellInfo> spellInfoClass;

private:
	UPanelWidget* m_container;
};
