// Project Lab - NHTV Igad

#pragma once

#include "Kismet/BlueprintFunctionLibrary.h"
#include "SoundFunctionLibrary.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API USoundFunctionLibrary : public UBlueprintFunctionLibrary
{
	GENERATED_BODY()
	

public:
	UFUNCTION(BlueprintCallable, Category = "Sound")
	static class ASoundEffect* CreateSoundEffect(class USoundBase* sndClass, class AActor* spawner);

	UFUNCTION(BlueprintCallable, Category = "Sound")
	static float GetSFXVolume(class UDefaultGameInstance* gameInstance);
	UFUNCTION(BlueprintCallable, Category = "Sound")
	static float GetMusicVolume(class UDefaultGameInstance* gameInstance);
};
