// Project Lab - NHTV Igad

#include "UnrealProject.h"

#include "DefaultGameState.h"
#include "MapData.h"

ADefaultGameState::ADefaultGameState()
{
	PrimaryActorTick.bCanEverTick = true;

	bReplicates = true;
}

void ADefaultGameState::BeginPlay()
{
	Super::BeginPlay();
}

void ADefaultGameState::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
}

void ADefaultGameState::GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const
{
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);

	DOREPLIFETIME(ADefaultGameState, gameEnded);
	DOREPLIFETIME(ADefaultGameState, gameWinningTeam);
	DOREPLIFETIME(ADefaultGameState, gameRestartingIn);
}