// Project Lab - NHTV Igad

#pragma once

#include "GameFramework/Actor.h"
#include "BossBarageBunny.generated.h"

UCLASS()
class UNREALPROJECT_API ABossBarageBunny : public ACharacter
{
	GENERATED_BODY()
	
public:	
	ABossBarageBunny();

	virtual void BeginPlay() override;
	
	virtual void Tick( float DeltaSeconds ) override;


	UPROPERTY(EditAnywhere, Category = "Bunny")
	class UParticleSystemComponent* BeamEmitter;

	UFUNCTION(BlueprintCallable, Category = "Bunny")
	void Setup(class AActor* boss, float lifeTime);

	UFUNCTION(BlueprintCallable, Category = "Bunny")
	void ClearBoss();


	UPROPERTY(Replicated)
	class AActor* boss;

private:
	float m_lifeTime;
};
