// Project Lab - NHTV Igad

#pragma once

#include "Blueprint/UserWidget.h"
#include "SizeBorder.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API USizeBorder : public UUserWidget
{
	GENERATED_BODY()
	
public:
	UPROPERTY(BlueprintReadOnly, Category = "Size")
	FVector2D pixelPosition;
	UPROPERTY(BlueprintReadOnly, Category = "Size")
	FVector2D pixelSize;
	UPROPERTY(BlueprintReadOnly, Category = "Size")
	FVector2D viewportPosition;
	UPROPERTY(BlueprintReadOnly, Category = "Size")
	FVector2D viewportSize;
	
	void NativeTick(const FGeometry& MyGeometry, float DeltaTime) override;
	
};
