// Project Lab - NHTV IGAD
//////////////////////////////////////////
// Author: Yoshi van Belkom - 130118
//////////////////////////////////////////
// The base Skill Tree Object.
//////////////////////////////////////////


#pragma once

#include "Engine/EngineTypes.h"
#include "HexMap.h"
#include "SkillTreeObject.generated.h"

UCLASS( BlueprintType, meta = (DisplayThumbnail = "true") )
class SKILLTREE_API USkillTreeObject : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	FHexMap hexMap;

	UPROPERTY( Category = SkillTree, EditAnywhere, AssetRegistrySearchable )
	TArray<TSubclassOf<class USkillObject>> skills;
};
