// Project Lab - NHTV Igad

#pragma once

#include "GameFramework/Actor.h"
#include "ParticleEffect.generated.h"

UCLASS()
class UNREALPROJECT_API AParticleEffect : public AActor
{
	GENERATED_BODY()

public:	
	AParticleEffect();

	virtual void BeginPlay() override;
	virtual void Tick( float DeltaSeconds ) override;

	void Init(UParticleSystem* particleSystem, float duration);

	UPROPERTY()
	UParticleSystemComponent* particleComponent;

	UPROPERTY(BlueprintReadWrite, Category = "Target")
	AActor* followActor;

	float duration;

};
