// Project Lab - NHTV Igad

#pragma once

#include "Blueprint/UserWidget.h"
#include "MiniMapVisionCircle.generated.h"

/**
 * 
 */
UCLASS()
class UNREALPROJECT_API UMiniMapVisionCircle : public UUserWidget
{
	GENERATED_BODY()
	
public:
	UMiniMapVisionCircle(const FObjectInitializer& init);

	virtual void NativeConstruct() override;

	UFUNCTION(BlueprintImplementableEvent, Category = "Vision")
	void SetTexture(UTexture2D* texture);

	UFUNCTION(BlueprintImplementableEvent, Category = "Vision")
	void SetUV(const FVector2D& uv, const FVector2D& scale);
};
