// Project Lab - NHTV Igad

#pragma once
#include "AbilityTriggerBase.h"
#include "GameFramework/Actor.h"
#include "ConeTrigger.generated.h"

UCLASS()
class UNREALPROJECT_API AConeTrigger : public AAbilityTriggerBase
{
	GENERATED_BODY()
	
public:	
	AConeTrigger();

	virtual void BeginPlay() override;
	virtual void Tick( float DeltaSeconds ) override;
	virtual bool CollisionCheck(ANetworkCharacter* otheractor) override;
	void SetCone(float radius, float angle);
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, meta = (ExposeOnSpawn), Category = "Trigger")
		float radius;
	UPROPERTY(VisibleAnywhere, BlueprintReadWrite, meta = (ExposeOnSpawn), Category = "Trigger")
		float angle;
private:
	UPROPERTY(VisibleAnywhere, Category = "Trigger")
	class UConeComponent* m_coneTrigger;
};
